/* tslint:disable */
/* eslint-disable */
/**
 * Timetable
 * What have you done today?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CurrentUser,
  LoginForm,
} from '../models';
import {
    CurrentUserFromJSON,
    CurrentUserToJSON,
    LoginFormFromJSON,
    LoginFormToJSON,
} from '../models';

export interface UserLoginRequest {
    loginForm: LoginForm;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * User login
     */
    async userLoginRaw(requestParameters: UserLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUser>> {
        if (requestParameters.loginForm === null || requestParameters.loginForm === undefined) {
            throw new runtime.RequiredError('loginForm','Required parameter requestParameters.loginForm was null or undefined when calling userLogin.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/user/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginFormToJSON(requestParameters.loginForm),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentUserFromJSON(jsonValue));
    }

    /**
     * User login
     */
    async userLogin(requestParameters: UserLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUser> {
        const response = await this.userLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
