/* tslint:disable */
/* eslint-disable */
/**
 * Timetable
 * What have you done today?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface GetEventCategories200Response
 */
export interface GetEventCategories200Response {
    /**
     * 
     * @type {Array<Category>}
     * @memberof GetEventCategories200Response
     */
    categories?: Array<Category>;
}

/**
 * Check if a given object implements the GetEventCategories200Response interface.
 */
export function instanceOfGetEventCategories200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetEventCategories200ResponseFromJSON(json: any): GetEventCategories200Response {
    return GetEventCategories200ResponseFromJSONTyped(json, false);
}

export function GetEventCategories200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventCategories200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': !exists(json, 'categories') ? undefined : ((json['categories'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function GetEventCategories200ResponseToJSON(value?: GetEventCategories200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': value.categories === undefined ? undefined : ((value.categories as Array<any>).map(CategoryToJSON)),
    };
}

