/* tslint:disable */
/* eslint-disable */
/**
 * Timetable
 * What have you done today?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginForm
 */
export interface LoginForm {
    /**
     * 
     * @type {string}
     * @memberof LoginForm
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof LoginForm
     */
    username: string;
}

/**
 * Check if a given object implements the LoginForm interface.
 */
export function instanceOfLoginForm(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function LoginFormFromJSON(json: any): LoginForm {
    return LoginFormFromJSONTyped(json, false);
}

export function LoginFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'username': json['username'],
    };
}

export function LoginFormToJSON(value?: LoginForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'username': value.username,
    };
}

