/* tslint:disable */
/* eslint-disable */
/**
 * Timetable
 * What have you done today?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveEvent200Response
 */
export interface SaveEvent200Response {
    /**
     * 
     * @type {number}
     * @memberof SaveEvent200Response
     */
    id?: number;
}

/**
 * Check if a given object implements the SaveEvent200Response interface.
 */
export function instanceOfSaveEvent200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SaveEvent200ResponseFromJSON(json: any): SaveEvent200Response {
    return SaveEvent200ResponseFromJSONTyped(json, false);
}

export function SaveEvent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveEvent200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function SaveEvent200ResponseToJSON(value?: SaveEvent200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

