name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: tar acf dist.tar.gz dist
      - uses: softprops/action-gh-release@v1
        with:
          files: dist.tar.gz
